name: Publish Layers

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Create All Lambda Layer Zip Files
      run: bash generate-layer-zip.sh

    - name: Publish layer-python-core
      run: aws lambda publish-layer-version --layer-name python-core --zip-file fileb://zipped-layers/layer-python-core.zip

    - name: Publish layer-python-crypto
      run: aws lambda publish-layer-version --layer-name python-crypto --zip-file fileb://zipped-layers/layer-python-crypto.zip

    - name: Publish layer-python-math
      run: aws lambda publish-layer-version --layer-name python-math --zip-file fileb://zipped-layers/layer-python-math.zip
